spring.application.name=frontend
server.port=${PORT:8081}

rest.base.url=${REST_BASE_URL:http://localhost:8080}
rest.user.name=${REST_USER_NAME:admin}
rest.user.password=${REST_USER_PASSWORD:admin}

management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true
management.health.livenessstate.enabled=true
management.health.readinessstate.enabled=true