apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: projektagile
spec:
  selector:
    app: backend
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: projektagile
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: projektagile-backend:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: PORT_BACKEND
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: SPRING_DATASOURCE_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: SPRING_DATASOURCE_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: SPRING_DATASOURCE_PASSWORD
            - name: SPRING_SECURITY_USER_NAME
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: SPRING_SECURITY_USER_NAME
            - name: SPRING_SECURITY_USER_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: SPRING_SECURITY_USER_PASSWORD