apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: projektagile
type: Opaque
stringData:
  SPRING_DATASOURCE_PASSWORD: "postgres"
  SPRING_SECURITY_USER_PASSWORD: "admin"
  REST_USER_PASSWORD: "admin"
  POSTGRES_PASSWORD: "postgres"
