apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "projektagile.labels" . | nindent 4 }}
type: Opaque
stringData:
  SPRING_DATASOURCE_PASSWORD: "{{ .Values.credentials.dbPassword }}"
  SPRING_SECURITY_USER_PASSWORD: "{{ .Values.credentials.adminPassword }}"
  REST_USER_PASSWORD: "{{ .Values.credentials.restPassword }}"
  POSTGRES_PASSWORD: "{{ .Values.credentials.dbPassword }}"
